export const english = {
  Common: {
    appWrapper: {
      gameRequestModal: {
        gameRequest: "Game request",
        challangerWantsToPlay: "{$challenger} would like to play with you",
      },
    },
    NotFound: {
      notFound: "404 Page not found",
      mainPage: "Main page",
    },
    Notifier: {
      accept: "Accept",
      info: "Info",
      close: "Close",
    },
    Home: {
      homeImage: "Home image",
    },
    Player: {
      userPicture: "User picture",
    },
    loginForm: {
      login: "Login",
      email: "E-mail address",
      password: "Password",
      submit: "Submit",
      haveNoAccount: "Don't have an account? ",
      registerHere: "Register here",
      errors: {
        empty_fields: "Fields cannot be empy",
      },
    },
    signupForm: {
      signup: "Sign Up",
      name: "Name",
      email: "E-mail address",
      password: "Password",
      submit: "Submit",
      haveAccount: "Already have an account? ",
      loginHere: "Login here",
      errors: {
        empty_fields: "Fields cannot be empy",
      },
    },
    leftSideBar: {
      noLogin: "Please login",
      userAvatar: "User avatar",
      logo: "logo",
      burgerButton: "Burger button",
      statuses: {
        playing: "PL",
        examining: "EX",
        playingTooltip: "Playing",
        examiningTooltip: "Examining",
        observing: "Observing",
      },
      notification: {
        pleaseFinishGame: "Now you are playing, please finish the game",
      },
    },
    gameListModal: {
      myGames: "My Games",
      players: "Players",
      result: "Result",
      date: "Date",
      pgn: "PGN",
      noDataFound: "No data found",
      resultWon: "Won",
      resultLost: "Lost",
      resultDrawn: "Drawn",
      resultUnknown: "Unknown",
      playersColumn: "{$white}-vs-{$black}",
      pgnIconAlt: "PgnDownload",
    },
    rightBarTop: {
      game: "Game",
      observe: "Observe",
      test: "Test",
      editor: "Editor",
      playComputer: "Play computer from here",
      play: "Play",
      tournaments: "Tournaments",
      quikpairing: "Quick Pairing",
      seekgame: "Seek a Game",
      matchuser: "Match User",
      gameShare: "Game share",
      gameDownload: "Game download",
      gameAnalysis: "Game Analysis",
      friends: "Friends",
      takeBack: "Take back",
      resign: "Resign",
      draw: "Draw",
      adjourn: "Adjourn",
      abort: "Abort",
      moveBackwardBeginning: "Move backward to the beginning",
      moveBackward: "Move backward",
      moveForward: "Move forward",
      moveForwardEnd: "Move forward to the end",
      flip: "Flip",
      inputCommand: "Input command",
      send: "Send",
    },
    menuLinkLabel: {
      play: "Play",
      learn: "Learn",
      connect: "Connect",
      examine: "Examine",
      topPlayers: "Top Players",
      logIn: "Log in",
      singUp: "Sign up",
      help: "Help",
      logout: "Logout",
      community: "Community",
      mygame: "My Games",
      uploadpgn: "Imported PGNs",
      users: "Users",
      last_ping: "Last ping",
      average_lag: "Average lag",
    },
    MoveList: {
      switchTable: "Table",
      switchString: "String",
    },
    MoveListComponent: {
      takeBack: "Take Back",
      draw: "Draw",
      resign: "Resign",
      abort: "Abort",
      Gamestatus: "Game status",
      examining: "Examining",
      playing: "Playing",
      action: "Action",
      addGameToLibrary: "Add game to library",
      complainAboutThisGame: "Complain about this game",
      emailGame: "Email game",
      rematch: "Rematch",
      examine: "Examine",
      editor: "Editor",
      newOpponent: "New opponent",
      takeBackMove: "TakeBack one move",
      takeBackMoves: "TakeBack two moves",
      flag: "Flag",
      moretime: "Moretime",
      adjourn: "Adjourn",
      playersColumn: "{$white}-vs-{$black}",
    },
    rightBarBottom: {
      chat: "Chat",
      events: "Events",
      friends: "Friends",
      fen_pgn: "FEN/PGN",
      history: "History",
      adjournedGame: "Adjourned Game",
      gameHistory: "Game History",
      gameLibrary: "Game Library",
      followCoach: "Follow Coach",
      examiner: "Examiner",
      observers: "Observers",
      roomChat: "Room chat",
      Observers: {
        players: "Players",
        result: "Result",
        date: "Date",
        status: "Status",
        playersColumn: "{$white}-vs-{$black}",
      },
      FollowCoach: {
        mail: "Mail",
        followers: "Followers",
        sendMessage: "Send message",
        follow: "Follow",
      },
    },
    MatchUserSubTab: {
      friends: "Friends",
      recentOpponent: "Recent Opponent",
      createChallangeLink: "Create challenge Link",
      chooseMember: "Option 1 - Choose a Member",
      sendLinkToAnyone: "Option 2 - Send a link for anyone to play",
      tenMin: "10 min",
      deleteSign: "Delete sign",
    },
    GameForm: {
      timeControl: "Time Control",
      minutes: "Minutes",
      secondPerMove: "Seconds per move",
      typeOfGame: "Type of Game",
      rated: "Rated",
      incrementOrDelayType: "Increment Or DelayType",
      inc: "Inc",
      us: "Us",
      bronstein: "Bronstein",
      pickAcolor: "Pick a color",
      white: "White",
      black: "Black",
      random: "Random",
      submit: "Submit",
    },
    GameRequestPopup: {
      accept: "Accept",
      decline: "Decline",
    },
    GamenotificationPopup: {
      close: "Close",
    },
    GameResignedPopup: {
      close: "Close",
    },
    ExaminActionPopup: {
      email: "Email",
      complaint: "Complaint",
      submit: "Submit",
    },
    ActionPopup: {},
    MainPage: {
      gamerequest: " has requested for a game",
      gameresign: "Opponent has resigned a game",
      halfmove: "Take Back 1 Move",
      fullmove: "Take Back 2 Moves",
      abort: "Abort",
      draw: "Draw",
      adjourn: "Adjourn",
      players: "Players",
      result: "Result",
      date: "Date",
      pgn: "PGN",
      playersVs: "{$white}-vs-{$black}",
      won: "Won",
      loss: "Loss",
    },
    MiddleBoard: {
      yourturn: "( Your Turn )",
      waitingforopponent: "( waiting for opponent )",
    },
    chatBoxMessage: {
      NEW_MESSAGE: "NEW MESSAGE",
      newGame: "NEW GAME",
      deleteSign: "Delete sign",
      sendSign: "Send sign",
    },
    pgnActions: {
      fen: "FEN",
      pgn: "PGN",
      pgnExport: "PGN Export",
      pgnImport: "PGN Import",
    },
    Events: {
      fen: "FEN",
      pgn: "PGN",
      pgnExport: "PGN Export",
      pgnImport: "PGN Import",
    },
  },
  Play: {
    PlayWithFriend: {
      PLAY_WITH_FRIEND: "Play with friend",
      BACK: "Back",
      FRIENDS: "Friends",
      CHOOSE: "Choose",
      CANCEL: "Cancel",
    },
    PlayFriendOptions: {
      PLAY_WITH_FRIEND: "Play with friend",
      BACK: "Back",
      FRIENDS: "Friends",
      CHOOSE: "Choose",
      createGame: "Create game",
      timeControl: "Time control",
      time_odds: "Time odds",
      challenger: "Challenger configuration",
      receiver: "Receiver configuration",
      control: {
        inc: "Inc",
        none: "None",
        us: "Us",
        bronstein: "Bronstein",
      },
      initial: "Initial",
      incrementOrDelay: "Increment or delay",
      ratingType: "Rating type",
      ratings: {
        none: "None",
        bullet: "Bullet",
        blitz: "Blitz",
        standard: "Standard",
      },
      color: "Color",
      colors: {
        random: "Random",
        white: "White",
        black: "Black",
      },
      isRated: "Rated",
      selectOpponent: "Select opponent",
    },
    PlayChooseBot: {
      time_odds: "Time odds",
      challenger: "Challenger configuration",
      receiver: "Receiver configuration",
      colors: {
        random: "Random",
        white: "White",
        black: "Black",
      },
      ratings: {
        none: "None",
        bullet: "Bullet",
        blitz: "Blitz",
        standard: "Standard",
      },
      playWithComputer: "Play with computer",
      back: "Back",
      difficulty: "Difficulty",
      color: "Color",
      timeControl: "Time control",
      control: {
        inc: "Inc",
        none: "None",
        us: "Us",
        bronstein: "Bronstein",
      },
      initial: "Initial",
      incrementOrDelay: "Increment or delay",
      ratingType: "Rating type",
      startTheGame: "Start the game",
    },
    PlaySeek: {
      dialogTitle: "Challenge",
      description: "{$username} ({$rating}) invites you to play the game",
      details: "{$time} • {$ratingType} • {$isRated} • {$color}",
      accept: "Accept",
      decline: "Decline",
      gameSeekSearching: "Searching for the game...",
      cancel: "Cancel",
    },
    PlayModaler: {
      rematch: "Rematch",
      examine: "Examine",
      whiteWon: "White won!",
      blackWon: "Black won!",
      gameDrawn: "Game drawn!",
      unknownResult: "Unknown result ",
      userImage: "User image",
    },
    PlayBlock: {
      createGame: "Create a game",
      playWithFriend: "Play with a friend",
      playWithComputer: "Play with the computer",
      seekButtons: {
        minute: "1 min",
        threeMinutes: "3 min (+2 sec inc)",
        fiveMinutes: "5 min",
        tenMinutes: "10 min",
        fifteenMinutes: "15 min",
        twentyMinutes: "20 min",
        twentyFiveMinutes: "25 min (+10 sec inc)",
      },
    },
    ObserveBlock: {
      inProgress: "Work in progress",
    },
    PlayRightSidebar: {
      tabs: {
        playTab: "Play",
        observeTab: "Observe",
      },
      bottomTabs: {
        chatTab: "Chat",
        kibitzTab: "Kibitz",
      },
    },
  },
  Editor: {
    EditorRightSidebar: {
      backToPlay: "Back to Play",
      boardSetUp: "Board set up",
      whiteToPlay: "White to play",
      blackToPlay: "Black to play",
      castling: "Castling",
      white: "White",
      black: "Black",
      startingPosition: "Starting position",
      clearBoard: "Clear board",
      flipBoard: "Flip board",
      fen: "FEN",
      insertFen: "Insert FEN here",
      whiteCastling: "White castling",
      blackCastling: "Black castling",
    },
  },
  Examine: {
    ExamineObserveTab: {
      findUsers: "Find user to observe",
      observe: "Observe",
    },
    ExamineObserverTabBlock: {
      observing: "{$quantity} people are observing {$username}'s board",
      unobserve: "Unobserve",
      user: "User",
      userAvatar: "User avatar",
    },
    ExamineOwnerTabBlock: {
      observing: "{$quantity} people are observing this board",
    },
    ExamineRightSidebarBottom: {
      tabs: {
        chat: "Chat",
        fenPgn: "FEN/PGN",
        games: "Games",
      },
      workInProgress: "Work in progress...",
    },
    FenPgn: {
      fen: "FEN",
      yourMessage: "Your message",
      pgn: "PGN",
      pgnImport: "PGN Import",
      pgnExport: "PGN Export",
      pgnSuccessfullyUploaded: "PGN successfully uploaded",
      importedGames: "Imported games",
    },
  },
  Community: {
    RoomBlock: {
      rooms: "Your rooms: {$rooms}",
      plus: "+",
      title: "Create room",
      plusTitle: "Create new room",
      joinRoom: "Join room with name {$roomName}",
    },
    CommunityRightBlock: {
      allRooms: "All rooms",
      close: "Close",
      createRoom: "Create room",
    },
    ChildChatInput: {
      send: "Send",
    },
    ChatInput: {
      send: "Send",
      yourMessage: "Your message",
    },
  },
  Profile: {
    ProfileDetailsCard: {
      cardTitle: "Profile details",
      uploadNewAvatar: "Upload new avatar",
      username: "Username",
      email: "E-mail",
      update: "Update",
      notifications: {
        usernameChanged: "Username was changed successfully",
        emailChanged: "E-mail was changed successfully",
        wrongEmail: "Wrong E-mail",
        fillEmail: "Please fill E-mail",
        fillUsername: "Please fill гsername",
        NOT_AUTHORIZED: "User has no authorized to change email",
      },
    },
    SecurityTab: {
      cardTitle: "Security",
      currentPassword: "Current password",
      newPassword: "New password",
      confirmPassword: "Confirm password",
      updatePassword: "Update password",
      notifications: {
        passwordChanged: "Password was changed successfully",
      },
      validation: {
        allValuesAreRequired: "All values are required",
        passwordsNotTheSame: "New passwords are not the same",
      },
    },
  },
  Users: {
    list: {
      userInfo: "User info",
      username: "Username",
      email: "E-mail",
      locale: "Locale",
      isolationGroup: "Isolation group",
      ratings: "Ratings",
      blitz: "Blitz",
      bullet: "Bullet",
      standard: "Standard",
      statuses: "Statuses",
      online: "Online",
      game: "Game",
      actions: "Actions",
      edit: "Edit",
    },
    edit: {
      details: {
        cardTitle: "Details",
        username: "Username",
        update: "Update",
      },
      security: {
        cardTitle: "Security",
        newPassword: "New password",
        confirmPassword: "Confirm password",
        isolationGroup: "Isolation group",
        update: "Update",
        errors: {
          allValuesAreRequired: "All values are required",
          passwordsNotTheSame: "New passwords are not the same",
        },
      },
    },
  },
};
