#!/bin/bash
NAME=oadubovskiy
V2URL=v2.chessclub.com
SANDBOX=sandbox.chessclub.com
SSH=~/.ssh/win/id_rsa
DB=iccserver

echo "start"
sudo ssh -fN -i $SSH -L 1234:localhost:27017 $NAME@$V2URL
echo "v2 connected"
mongodump --port=1234 -d $DB
ps aux | grep -i ssh | grep 1234:localhost:27017 | awk '{print $2}' | xargs sudo kill -9
echo "imported"

sudo ssh -fN -i $SSH -L 1235:localhost:27017 $NAME@$SANDBOX
mongorestore dump/iccserver --port=1235 --drop -d $DB
mongo localhost:1235/$DB < ./db/db.js
ps aux | grep -i ssh | grep 1235:localhost:27017 | awk '{print $2}' | xargs sudo kill -9
echo "exported"
rm -r dump
echo "done"
