# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Staging deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.17.3
      uses: actions/setup-node@v2
      with:
        node-version: "14.17.3"
        cache: 'npm'
    - run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
    - run: npm install --global meteor
    - run: npm i --global mup
    - run: npm install
    - run: meteor npm install
    - name: OpenVPN-Connect
      uses: kota65535/github-openvpn-connect-action@v1.0.2
      with:
        config_file: $config_file
        username: "fake_username"
        password: "fake_pass"
        tls_auth_key: "fake"
        client_key: "fake"
    - name: Deploy with meteor-up
    - run: cd .deploy/
    - run: mup deploy
